server:
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 200
      min-spare: 30
  port: 8080
  servlet:
    #配置路径
    context-path: /emos-wx-api
spring:
  datasource:
    # 用阿里巴巴连接池 这样的话 mybatis 要导入一个特定名字的包
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: root
      # 这些配置要搭配本地cpu与内存
      initial-size: 4
      max-active: 4
      #      最小空闲数
      min-idle: 2
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  data:
    mongodb:
      uri: mongodb://yu:root@1.15.44.134:27017
      database: imooc-news
#      host: 1.15.44.134
#      port: 27137
#      database: yu
#      authentication-database: emos
#      username: yu
#      password: root
  redis:
    database: 0
    host: 1.15.44.134
    port: 6379
    password: yuze123
    jedis:
      pool:
        max-active: 1000
        #不设置最大等待时间
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  mail:
    # 发邮件用的 其实这里就没用这个功能
    default-encoding: UTF-8
    host: smtp.163.com
    username: x@163.com
    password: XXxx
mybatis:
  mapper-locations: classpath*:mapper/*.xml #  **表示可以表示任意多级目录。
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    # 输出格式？
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名法开启 和实体类搭配？
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.ex.db.dao: warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"
swagger2:
  enable=true:

# JwtUtil类 用到了
emos:
  jwt:
    #密钥
    secret: 123456
    #令牌过期时间（天）
    expire: 5
    #令牌缓存时间（天数）
    cache-expire: 10
  email:
    system: x@qq.com
    hr: x@qq.com
  image-folder: C:\Users\27890\Desktop\imooc\emos\images
  code: HelloWorld
  recieveNotify: http://192.168.1.115:8080/emos-wx-api/meeting/recieveNotify



wx:
  app-id: wx1b864d35606dbb4b
  secret: 122a95ccc9e2ba25541a7a3b955dcb11

aliyun:
  alikey: LTAI5tDJ2sSDuZ2vUTnZsBQc
  alisecret: 3cKqAmpGCJvZOoooIb8ctPie9QoZxm